[theme]
primaryColor = "#4A90E2"             # bleu doux pour les accents
backgroundColor = "#FFFFFF"          # fond blanc pur
secondaryBackgroundColor = "#F6F8FA" # léger gris pour les conteneurs
textColor = "#111517"                # texte sombre
font = "sans serif"
